enum{
COPY,
COPY_CONSTANT,
COPY_PROGRAM_TO_DATA,
COPY_DATA_TO_PROGRAM,
GO_TO,

SET_SOURCE,
SET_DESTINATION,

ADD,
ADD_CONSTANT,
SUBTRACT,
SUBTRACT_CONSTANT,
MULTIPLY,
MULTIPLY_CONSTANT,
DIVIDE,
DIVIDE_CONSTANT,

START_HEAD_AT,
END_HEAD,

NUMBER_OF_PROGRAMS
};

#define DATA_TYPE unsigned int

#define DEFAULT_SIZE  32
#define MAX_VALUE     0xFFFFFFFF
#define PROGRAM_CHUNK_SIZE 1024

struct VECTOR{
  DATA_TYPE* data;
  DATA_TYPE  capacity;
};

//SHORTCUTS

#define FLAGS 0

// REGISTERS
#define OVERFLOW 0
#define UNDERFLOW 1
#define REMAINDER 2
#define PROGRAM_RESIZE_FAILED 4

#define AT_HEAD_OFFSET(x) program[(heads[head_index] + x)/PROGRAM_CHUNK_SIZE][(heads[head_index] + x)%PROGRAM_CHUNK_SIZE]
#define PROGRAM_AT(x)     program[x/PROGRAM_CHUNK_SIZE][x%PROGRAM_CHUNK_SIZE]
#define DATA_AT(x,y)      data[x].data[y]
#define FLAG_AT(x)        data[FLAGS].data[x]
