enum{
COPY,
COPY_CONSTANT,
COPY_PROGRAM_TO_DATA,
COPY_DATA_TO_PROGRAM,
GO_TO,

SET_SOURCE,
SET_DESTINATION,

ADD,
ADD_CONSTANT,
SUBTRACT,
SUBTRACT_CONSTANT,
MULTIPLY,
MULTIPLY_CONSTANT,
DIVIDE,
DIVIDE_CONSTANT,
REMAINDER,
REMAINDER_CONSTANT,

START_HEAD_AT,
END_HEAD,
GET_HEAD,

NUMBER_OF_PROGRAMS
};

#define DATA_TYPE unsigned int

#define DEFAULT_SIZE  32
#define MAX_VALUE     0xFFFFFFFF

struct VECTOR{
  DATA_TYPE* data;
  DATA_TYPE  capacity;
};

//SHORTCUTS

#define SETTINGS 0
#define FLAGS 1

// REGISTERS
#define OVERFLOW 0
#define UNDERFLOW 1
#define DIVISION_BY_ZERO 2
#define PROGRAM_RESIZE_FAILED 3

#define DATA_AT(x,y)      data[x].data[y]
#define FLAG_AT(name)        data[FLAGS].data[name]
#define SETTING_AT(name) data[SETTINGS].data[name]
#define AT_HEAD_OFFSET(x) program[(heads[head_index] + x)/SETTING_AT(PROGRAM_CHUNK_SIZE)][(heads[head_index] + x)%SETTING_AT(PROGRAM_CHUNK_SIZE)]
#define PROGRAM_AT(x)     program[x/SETTING_AT(PROGRAM_CHUNK_SIZE)][x%SETTING_AT(PROGRAM_CHUNK_SIZE)]
