0,
1,
//GET_CURRENT_INDEX


//OPERATION
OPERATION, EMPTY, EMPTY, EMPTY, EMPTY,

//ADVANCE MODES
SUBTRACT, NEGATIVE_RELATIVE,4, IMMEDIATE,NUMBER_OF_INDEX_MODES,
SET_PRIMARY,FLAGS,
IF,UNDERFLOW,5,
SET_PRIMARY,NUMBER_OF_DEFAULT_ARRAYS,
GO_TO_INDEX, POSITIVE_RELATIVE,6,
ADD, NEGATIVE_RELATIVE,4, IMMEDIATE,1,

SUBTRACT, NEGATIVE_RELATIVE,10, IMMEDIATE, NUMBER_OF_INDEX_MODES,
SET_PRIMARY, FLAGS,
IF,UNDERFLOW,5,
SET_PRIMARY, NUMBER_OF_DEFAULT_ARRAYS,
GO_TO_INDEX,POSITIVE_RELATIVE,6,
ADD, NEGATIVE_RELATIVE,2, IMMEDIATE,1,

GO_TO_INDEX, NEGATIVE_RELATIVE, EMPTY ,
