#define PROGRAM_CODE 1
#define SOURCE_VECTOR 7
#define DESTINATION_VECTOR 31
#define DATA_VECTOR 30

#define LOOP_START 14
#define LOOP_END 40
#define VECTOR_ITER 25

DATA_TYPE test_program[] = {

  SET_DESTINATION, DATA_VECTOR,
  COPY_CONSTANT, LOOP_START, 0,

  GET_ARRAY_CAPACITY, 7, 1,

  SET_SOURCE, DATA_VECTOR,
  COPY, 1, 2,

//loop start

  COPY_DATA_TO_PROGRAM, 2, VECTOR_ITER,
  COPY_DATA_TO_PROGRAM, 2, VECTOR_ITER+1,

  SET_DESTINATION, DESTINATION_VECTOR,
  SET_SOURCE, SOURCE_VECTOR,
  COPY, 0, 0,

  SET_DESTINATION, DATA_VECTOR,
  SUBTRACT_CONSTANT, 2, 1,

  //decide to loop back or jump out

  SET_SOURCE, DATA_VECTOR,
  GO_TO, 0,

};
