DATA_TYPE test_program[] = {
  SET_SOURCE, NUMBER_OF_DEFAULT_ARRAYS,
  SET_DESTINATION, NUMBER_OF_DEFAULT_ARRAYS,
  SET_FAILSAFE_TYPE, 3,
  
  EMPTY, EMPTY, EMPTY,  

  INSERT_ARRAY, EMPTY, EMPTY,

  SET_TRANSFER_TYPE, 2,
  
  ADD_CONSTANT, 6, 1,

  GO_TO, 6, 
  
  EXIT
};
