DATA_TYPE test_program[] = {
  EMPTY,
  
  SET_SOURCE, NUMBER_OF_DEFAULT_ARRAYS,
  SET_DESTINATION, NUMBER_OF_DEFAULT_ARRAYS+1,

  COPY, 2, 1,

  GO_TO_ARRAY, NUMBER_OF_DEFAULT_ARRAYS+1,
  GO_TO_INDEX, 15,
  
  EXIT
};
